# Generated by Django 5.2.1 on 2025-06-11 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_contact_birth_date_contact_birth_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Campaign Name')),
                ('message_text', models.TextField(verbose_name='Message Text')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Attachment (optional)')),
                ('scheduled_at', models.DateTimeField(verbose_name='Scheduled Date & Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.group', verbose_name='Target Group')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
    ]
