# Generated by Django 5.2.1 on 2025-06-11 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=10)),
                ('reaction_status', models.CharField(blank=True, choices=[('not_delivered', 'Sent but not delivered'), ('delivered_unread', 'Delivered, unread'), ('read', 'Read'), ('replied', 'Replied'), ('reacted', 'Reacted')], max_length=20, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaign.campaign')),
            ],
        ),
    ]
